version: '3'
 
services:
  gdrive:
    build: .
    image: google-drive-ocamlfuse
    restart: always
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    cap_add:
      - mknod
      - sys_admin
    environment:
      ACCOUNT_foo: 1001

      PUID: 1001
      PGID: 1001
    volumes:
      - /mnt/gdrive:/data:shared
      - ./config:/root/.gdfuse