version: '3'
 
services:
  gdrive:
    build: .
    image: servercontainers/google-drive-ocamlfuse
    restart: always
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    cap_add:
      - mknod
      - sys_admin
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /mnt/gdrive:/data:shared
      - ./config:/root/.gdfuse